name: "Build"

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop .#test
    - run: just test
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-artifacts
        path: result/bin
